=== Nordix/anchore-engine/tests/functional/services/policy_engine/schema_files/vulnerability_report.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "vulnerability_report.schema.json",
  "definitions": {
    "nvd_data_entry": {
      "type": "object",
      "properties": {
        "cvss_v2": {
          "type": "object",
          "properties": {
            "additional_information": {
              "type": "object",
              "properties": {
                "ac_insuf_info": {
                  "type": ["null","boolean"]
                },
                "obtain_all_privilege": {
                  "type": "boolean"
                },
                "obtain_other_privilege": {
                  "type": "boolean"
                },
                "obtain_user_privilege": {
                  "type": "boolean"
                },
                "user_interaction_required": {
                  "type": "boolean"
                }
              }
            },
            "base_metrics": {
              "type": "object",
              "properties": {
                "access_complexity": {
                  "type": "string"
                },
                "access_vector": {
                  "type": "string"
                },
                "authentication": {
                  "type": "string"
                },
                "availability_impact": {
                  "type": "string"
                },
                "base_score": {
                  "type": "number"
                },
                "confidentiality_impact": {
                  "type": "string"
                },
                "exploitability_score": {
                  "type": "number"
                },
                "impact_score": {
                  "type": "number"
                },
                "integrity_impact": {
                  "type": "string"
                }
              }
            },
            "severity": {
              "type": "string"
            },
            "vector_string": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          }
        },
        "cvss_v3": {
          "type": "object",
          "properties": {
            "base_metrics": {
              "type": "object",
              "properties": {
                "attack_complexity": {
                  "type": "string"
                },
                "attack_vector": {
                  "type": "string"
                },
                "availability_impact": {
                  "type": "string"
                },
                "base_score": {
                  "type": "number"
                },
                "base_severity": {
                  "type": "string"
                },
                "confidentiality_impact": {
                  "type": "string"
                },
                "exploitability_score": {
                  "type": "number"
                },
                "impact_score": {
                  "type": "number"
                },
                "integrity_impact": {
                  "type": "string"
                },
                "privileges_required": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "user_interaction": {
                  "type": "string"
                }
              }
            },
            "vector_string": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "string"
        }
      }
    },
    "cpe_entry": {
      "type": "object",
      "properties": {
        "cpe": {
          "type": "string"
        },
        "cpe23": {
          "type": "string"
        },
        "feed_name": {
          "type": "string"
        },
        "feed_namespace": {
          "type": "string"
        },
        "fixed_in": {
          "type": "array"
        },
        "link": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "nvd_data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/nvd_data_entry"
          }
        },
        "pkg_path": {
          "type": "string"
        },
        "pkg_type": {
          "type": "string"
        },
        "severity": {
          "type": "string"
        },
        "vendor_data": {
          "type": "array"
        },
        "version": {
          "type": "string"
        },
        "vulnerability_id": {
          "type": "string"
        }
      }
    },
    "cpe_report": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cpe_entry"
      }
    },
    "legacy_table": {
      "type": "object",
      "required": ["colcount", "header", "rowcount", "rows"],
      "properties": {
        "colcount": {
          "$ref": "#/definitions/legacy_table_colcount"
        },
        "header": {
          "$ref": "#/definitions/legacy_table_header"
        },
        "rowcount": {
          "$ref": "#/definitions/legacy_table_rowcount"
        },
        "rows": {
          "$ref": "#/definitions/legacy_table_rows"
        }
      }
    },
    "legacy_table_colcount": {
      "type": "number"
    },
    "legacy_table_header": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "legacy_table_rowcount": {
      "type": "number"
    },
    "legacy_table_rows": {
      "type": "array",
      "items": {
        "type": "array",
        "items": [
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "number"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          }
        ]
      }
    },
    "legacy_report": {
      "type": "object",
      "required": ["multi"],
      "properties": {
        "multi": {
          "type": "object",
          "required": ["result", "url_column_index", "warns"],
          "properties": {
            "result": {
              "$ref": "#/definitions/legacy_table"
            },
            "url_column_index": {
              "type": "number"
            },
            "warns": {
              "type": "array"
            }
          }
        }
      }
    }
  },
  "type": "object",
  "required": ["cpe_report", "image_id", "legacy_report", "user_id"],
  "properties": {
    "cpe_report": {
      "$ref": "#/definitions/cpe_report"
    },
    "image_id": {
      "type": "string"
    },
    "legacy_report": {
      "$ref": "#/definitions/legacy_report"
    },
    "user_id": {
      "type": "string"
    }
  }
}

=== Nordix/anchore-engine/tests/functional/services/policy_engine/expected_output/sha256:4661fb57f7890b9145907a1fe2555091d333ff3d28db86c3bb906f6a2be93c87.json
{"cpe_report": [], "image_id": "28f6e27057430ed2a40dbdd50d2736a3f0a295924016e294938110eeb8439818", "legacy_report": {"multi": {"result": {"colcount": 15, "header": ["CVE_ID", "Severity", "*Total_Affected", "Vulnerable_Package", "Fix_Available", "Fix_Images", "Rebuild_Images", "URL", "Package_Type", "Feed", "Feed_Group", "Package_Name", "Package_Path", "Package_Version", "CVES"], "rowcount": 0, "rows": []}, "url_column_index": 7, "warns": []}}, "user_id": "admin"}
